---
name: build
"on": [push, pull_request]
jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: Kaniko build
        uses: aevea/action-kaniko@v0.12.0
        with:
          image: gitea.clark-evans.com/milamber/harvester-backup
          username: ${{ secrets.PACKAGEPUSHUSER }}
          password: ${{ secrets.PACKAGEPUSHTOKEN }}
          # cache: true
          # cache_registry: aevea/cache
