---
name: build
"on":
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: jaecontainers/harvester-auto-backup
          tags: |
            type=semver,pattern={{ version }}
            type=semver,pattern={{ major.minor }}
            type=semver,pattern={{ major }}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
