---
name: checks
"on":
  - push
  - pull_request
jobs:
  check:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: "Yamllint"
        uses: karancode/yamllint-github-action@master
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
